<a href="https://colab.research.google.com/github/NGuerrero23/TT-2C2025-Data-Analitycs-Notebooks/blob/main/Clase_3/Resolucion_Clase_03_NB2_Import_datasets_con_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos para importar datasets con Pandas

Links que vamos a usar:

* [Blog Kaggle - International Hotel Booking Analytics](https://www.kaggle.com/code/sonawanelalitsunil/international-hotel-booking-analytics-ml-34-75/notebook)
* [Datasets Kaggle - International Hotel Booking Analytics](https://www.kaggle.com/datasets/alperenmyung/international-hotel-booking-analytics)
* [Dataset Github - LifeExpectancy ](https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv)
* [Dataset Kaggle - Netflix](https://www.kaggle.com/datasets/shivamb/netflix-shows/code)

# 1. Descargar los datasets (archivos .csv) antes de comenzar

* Opción 1:
Decargarlos desde el Repositorio Oficial del Curso [Click Aquí](https://drive.google.com/drive/folders/1LI3HcSqcrSJ52YZAoQG0NNmdOnHVSJHG)
* Opción 2:
Decargarlos desde Kaggle [Click Aquí](https://www.kaggle.com/datasets/alperenmyung/international-hotel-booking-analytics) - Haciendo click en el botón Download/Descargar (Debe descomprimir el archivo "archive.zip")

# 2. Preparar los archivos en Google Drive

1. Crear en su unidad de Google Drive la carpeta "datasets"
2. Subir a esa carpeta los archivos:
* hotels.csv
* reviews.csv
* users.csv

# 3 Montar y liberar la unidad

Este código permite montar la unidad de su Drive en este ambiente virtual de Colab

In [2]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Al finalizar la actividad o en caso que lo requiera, puede desmontar la unidad con este código

In [20]:
# Liberar la unidad
drive.flush_and_unmount()

# 4. Importar datasets

A continuación veremos varias opciones para importar datasets a Google Colab usando Pandas, el método dependerá de la necesidad y de sus conocimientos, por ello se plantean varios escenarios para cada nivel.

## 4.1 Importar datasets desde Google Sheets  (Nivel Inicial) - no necesita montar disco del Drive

In [3]:
# Importar la librería Pandas
import pandas as pd

In [21]:
# Acceso a Gsheets - Metodo con URL de conversion a CSV (lectura)
# El archivo debe tener permisos de lectura para TODOS
#https://docs.google.com/spreadsheets/d/177DGqfoviiA6nTcSUO0Ng2Bbc9aad6-0IjcX_kNpNoY/edit?gid=2107498576#gid=2107498576
ID_planilla = '177DGqfoviiA6nTcSUO0Ng2Bbc9aad6-0IjcX_kNpNoY'
URL = f'https://docs.google.com/spreadsheets/d/{ID_planilla}/gviz/tq?tqx=out:csv&sheet='
df_gs = pd.read_csv(URL + 'ventas')   #gs = google sheets; df = dataframe; ...URL + 'la hoja que quiera importar'
df_gs.head()

,hotel_id,hotel_name,city,country,star_rating,lat,lon,cleanliness_base,comfort_base,facilities_base,location_base,staff_base,value_for_money_base
0,1,The Azure Tower,New York,United States,5,40.7580,-73.9855,9.1,8.8,8.9,9.5,8.6,8.0
1,2,The Royal Compass,London,United Kingdom,5,51.5072,-0.1276,9.0,9.2,8.8,9.4,9.0,7.9
2,3,L'Étoile Palace,Paris,France,5,48.8566,2.3522,8.8,9.4,8.7,9.6,9.3,8.1
3,4,Kyo-to Grand,Tokyo,Japan,5,35.6895,139.6917,9.6,9.0,9.3,8.5,9.5,8.2
4,5,The Golden Oasis,Dubai,United Arab Emirates,5,25.2769,55.2962,9.3,9.5,9.6,8.9,9.4,8.5

## 4.2 Importar datasets desde Google Drive  (Nivel Inicial)

En esta instancia, ya deberías tener creada la carpeta `datasets` en el raíz de tu Unidad de Google Drive, y ahi haber subido los archivos csv que vamos a usar

In [ ]:
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/Colab_Notebooks/datasets")

In [12]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
# Usar el método read_csv de Pandas (pd) que recibe como argumento el archivo csv y retorna un dataframe
df_users = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/datasets/users.csv')
df_users.head()

## 4.3 Importar datasets desde Google Drive (Nivel Intermedio)

Si van a trabajar con datasets que se encuentran en diferentes carpetas, puden cambiar la ruta por defecto

1. Se sugiere usar el panel de navegación laterar para explorar las carpetas y sus archivos.
2. Cambiar la ruta original al directorio donde se encuentran los archivos .csv que se quieren importar

In [ ]:
# Validar la ruta y la existencia del archivo csv a importar
import os
os.chdir("/content/drive/MyDrive/Colab_Notebooks/datasets")
os.listdir(".")

In [ ]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
# Usar el método read_csv de Pandas (pd) que recibe como argumento el archivo csv y retorna un dataframe
df = pd.read_csv('users.csv')
df.head()

## 4.4 Importar datasets desde Github

In [22]:
# Cargar en una variable la URL del archivo csv de Github
url = "https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv"

In [6]:
# Importar la librería Pandas
import pandas as pd

In [24]:
# Usar el método read_csv de Pandas (pd) que recibe como argumento el archivo csv y retorna un dataframe
df_github = pd.read_csv(url)
df_github.head()

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

## 4.5 Importar Datasets públicos desde Kaggle (Nivel Avanzado)


> Para datasets públicos que no requieren autenticación

Cuando quieran descargar un dataset público desde Kaggle, hacer click en download y pegrn el código "Download Via kagglehub"
<BR>
En este caso vamos a descargar el dataset [Netflix Movies](https://www.kaggle.com/datasets/shivamb/netflix-shows/code)

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivamb/netflix-shows")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'netflix-shows' dataset.
Path to dataset files: /kaggle/input/netflix-shows

Kagglehub descarga sus archivos en un cache, path informa la ruta.
<BR>
Lo que hacemos es copiarlo a la carpeta "datasets" de nuestro drive

In [2]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os, shutil
# Carpeta destino
dest_dir = "/content/drive/MyDrive/Colab_Notebooks/datasets/"

# Copiar todos los archivos del dataset al destino
for file in os.listdir(path):
    shutil.copy(os.path.join(path, file), dest_dir)

print("Archivos copiados a:", dest_dir)
print("Contenido:", os.listdir(dest_dir))

Archivos copiados a: /content/drive/MyDrive/Colab_Notebooks/datasets/
Contenido: ['hotels.gsheet', 'users.csv', 'reviews.csv', 'hotels.csv', 'netflix_titles.csv']

In [7]:
# Usar el método read_csv de Pandas (pd) que recibe como argumento el archivo csv y retorna un dataframe
df = pd.read_csv(f"{path}/netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## 4.6 Importar Datasets privados desde Kaggle (Nivel Avanzado)


> Para datasets privados que si requieren autenticación

Crear una carpeta en el raíz del Drive llamada `kaggle` y pegar el archivo `kaggle.json` (API Token) que generan desde su perfil de Kaggle

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Validar la existencia del JSON
import os
os.listdir("/content/drive/MyDrive/kaggle")

Este código crear una carpeta kaggle en el raíz y la segunda linea un copy/paste de `kaggle.json`

In [ ]:
!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/kaggle/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

En este caso vamos a descargar el mismo dataset [Netflix Movies](https://www.kaggle.com/datasets/shivamb/netflix-shows/code)
<BR>
Aunque al ser público esto no es necesario

In [ ]:
# Este código descarga el dataset con las credenciales
!kaggle datasets download -d shivamb/netflix-shows -p /content/drive/MyDrive/datasets
!unzip /content/drive/MyDrive/datasets/netflix-shows.zip -d /content/drive/MyDrive/datasets

In [ ]:
# Validar la existencia del archivo descargado
import os
os.listdir("/content/drive/MyDrive/datasets")

In [ ]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/datasets/netflix_titles.csv")
print(df.shape)   # filas y columnas
df.head()         # primeras 5 filas

## 4.7 Importar Datos desde una base de datos relacional ya subida a la carpeta datasets del raíz

En esta modalidad, deben descargar la carpeta zip desde desde este link
<BR>
[Descargar](https://www.kaggle.com/datasets/alperenmyung/international-hotel-booking-analytics)
<BR>
Descomprimir la carpeta y subir el archivo `booking_db.sqlite` a la carpeta `/datasets` de su Drive

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Validar la existencia de la DB
import os
os.listdir("/content/drive/MyDrive/datasets")

['netflix-shows.zip',
 'international-hotel-booking-analytics.zip',
 'netflix_titles.csv',
 'satis_clientes.csv',
 'sakila.db',
 'booking_db_nulls.sqlite',
 'booking_db.sqlite',
 'users.csv',
 'hotels.csv',
 'reviews.csv']

In [ ]:
# Importamos las librerías
import sqlite3
import pandas as pd

In [ ]:
# Establecemos la conexión a la db
conexion = sqlite3.connect('/content/drive/MyDrive/datasets/booking_db.sqlite')

In [ ]:
df = pd.read_sql('''
    SELECT
        *
    FROM reviews
    ;
''', conexion, index_col='review_id', parse_dates=['review_date'])

In [ ]:
df.info()

In [ ]:
sql_query = """
    SELECT
    review_id, hotel_name, city, star_rating, score_overall, u.country, r.review_date
    FROM hotels h
    join reviews r on h.hotel_id = r.hotel_id
    join users u on r.user_id = u.user_id
    order by score_overall asc
    ;
"""

df = pd.read_sql(sql_query, conexion, index_col='review_id')

In [ ]:
df = pd.read_sql('''
    SELECT
    review_id, hotel_name, city, avg(score_overall)
    FROM hotels h
    join reviews r on h.hotel_id = r.hotel_id
    group by hotel_name, city
    order by avg(score_overall) desc
    ;
''', conexion, index_col='review_id')

## 4.8 Importar Datos desde una base de datos relacional (usando credenciales de Kaggle - descarga directa)

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Validar la existencia del JSON
import os
os.listdir("/content/drive/MyDrive/kaggle")

In [ ]:
# Creamos una carpeta temporal en el ambiente virtual
!mkdir -p ~/.kaggle
# ahí pegamos las credenciales
!cp /content/drive/MyDrive/kaggle/kaggle.json ~/.kaggle/
# cambiamos los permisos
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
# Este código descarga el dataset con las credenciales a la carpeta datasets
!kaggle datasets download -d alperenmyung/international-hotel-booking-analytics -p /content/drive/MyDrive/datasets
# y con esta línea hacemos el unzip
!unzip /content/drive/MyDrive/datasets/international-hotel-booking-analytics.zip -d /content/drive/MyDrive/datasets

In [ ]:
# Importamos las librerías
import sqlite3
import pandas as pd

In [ ]:
# Establecemos la conexión a la db
conexion = sqlite3.connect('/content/drive/MyDrive/datasets/booking_db.sqlite')

In [ ]:
df = pd.read_sql('''
    SELECT
        *
    FROM reviews
    ;
''', conexion, index_col='review_id', parse_dates=['review_date'])

In [ ]:
df = pd.read_sql('''
    SELECT
    review_id, hotel_name, city, star_rating, score_overall, u.country
    FROM hotels h
    join reviews r on h.hotel_id = r.hotel_id
    join users u on r.user_id = u.user_id
    order by score_overall asc
    ;
''', conn, index_col='review_id')

In [ ]:
df = pd.read_sql('''
    SELECT
    review_id, hotel_name, city, avg(score_overall)
    FROM hotels h
    join reviews r on h.hotel_id = r.hotel_id
    group by hotel_name, city
    order by avg(score_overall) desc
    ;
''', conn, index_col='review_id')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.describe()